# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: setup-lxd
  # You may pin to the exact commit or the version.
  # uses: whywaita/setup-lxd@8205f1cf8b5e9e79051dcc9054a12e2e25ca15b4
      uses: whywaita/setup-lxd@v1
      with:
        lxd_version: default
    - name: recupération
      run: echo "hey" >> lxc config trust add >>hey
    - name: test1
      run: cat hey
           
    - name: Build
      run: go build 

    - name: Test
      run: go test 
  
