# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'
    - name: Install LXD
      run: |
        #snap help refresh
        #sudo snap install lxd
        sudo lxd init --auto --network-address=0.0.0.0 --network-port=8443
        sudo lxc launch ubuntu:22.04 ubuntu-container

    #- name: Start LXD or Initialize if not started
     # run: |
      #  sudo systemctl start lxd || (systemctl status lxd && exit 1) || sudo lxd init --auto
      
    #- name: lxd init
     # run: systemctl start lxd || systemctl status lxd || sudo lxd init --auto
    #- name: test1
      #run: ls && echo "hey" | lxc config trust add >>hey2
   
    - name: Build
      run: go build 

    - name: Test
      run: go test 
  
