# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "feat/terminal" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: go build 
    - name: droit
      run: cd ../../ && pwd && ls #cp ~/tls/* tls/ && go build
    - name: Test
      run: go test 
      
