# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
       
   # - name: Set up Go
    #  uses: actions/setup-go@v4
     # with:
      #  go-version: '1.21.5'
    - name: Install LXD
    
      run: 
        #snap help refresh
        #sudo snap install lxd
        cat config.yaml | sudo lxd init --preseed 
        #sudo lxc launch ubuntu:22.04 ubuntu-container
      working-directory: test
    - name: Start LXD or Initialize if not started
      run: |
       snap info lxd
       
    - name: test1
      run: #echo "hey" | lxc config trust add >>hey2
          ls /var/snap/lxd/common/
   
    - name: Build
      run: go build 

    - name: Test
      run: go test 
  
